//! Qt-free core of the Clarp Rust desktop client: wire types, the SSE parser,
//! the conversation sync and delivery reducers, and transcript text rules.
//! Everything here is pure so `cargo test` needs no display or Qt runtime.

pub mod agent_prompt;
pub mod attachments;
pub mod audio;
pub mod audio_journal;
pub mod avatar_motion;
pub mod catalog;
pub mod conversation;
pub mod decision_receipt;
pub mod delivery;
pub mod diagnostics;
pub mod directory;
pub mod endpoint;
pub mod form_events;
pub mod jobs;
pub mod json;
pub mod instance;
pub mod launch;
pub mod links;
pub mod list_ops;
pub mod live;
pub mod history_fold;
pub mod live_present;
pub mod markdown_style;
pub mod media;
pub mod narrator;
pub mod panes;
pub mod presentation;
pub mod presence;
pub mod preview;
pub mod protocol;
pub mod reading_theme;
pub mod readability;
pub mod roster;
pub mod settings;
pub mod sidebar;
pub mod sse;
pub mod stream_text;
pub mod sync;
pub mod text;
pub mod transcript_cache;
pub mod transcript_layout;
pub mod transcript_rows;
pub mod time_format;
pub mod tree;
pub mod workspace;
